### ISSUE TITLE
Implement StarkConfig Validation Functionality

### ISSUE THREAD

**Issue by Okm165** [HerodotusDev/cairo-verifier#22]
We are initiating a task to develop a validation function for StarkConfig objects. This function, to be named `stark_config_validate`, will be responsible for ensuring the integrity and correctness of StarkConfig objects. It will include a series of checks and validations tailored to our specific operational and security needs.
Reference: https://vscode.dev/github/Okm165/cairo-lang/blob/v0.11.0-run-proof-sw-patch/cairo-lang-0.11.0/starkware/cairo/stark_verifier/core/config.cairo#L42

**Comment by neotheprogramist** [comment]
Functions that needs to be implemented:
- [ ] stark_config_validate
- [ ] proof_of_work_config_validate
- [ ] traces_config_validate
- [ ] validate_vector_commitment
- [ ] fri_config_validate
- [ ] fri_layers_config_validate
