### ISSUE TITLE
Successfully verify a Stone proof using the cairo0 verifier 

### ISSUE THREAD

**Issue by tiagofneto** [HerodotusDev/cairo-verifier#4]

**Comment by Okm165** [comment]
Repository with the working example here: https://github.com/Okm165/stone-prover-cairo0-verifier

**Comment by Okm165** [comment]
It is not trivial to move to v0.12.0 but i will develop this in future

**Comment by Okm165** [comment]
Repository: https://github.com/Okm165/stone-prover-cairo0-verifier
now works on cairo-lang v0.12.0 & stone-prover v0.12.0
