### ISSUE TITLE
Verify Proof of Work / Grinding

### ISSUE THREAD

**Issue by tiagofneto** [HerodotusDev/cairo-verifier#7]
Described in ethSTARK paper 3.11.3.

Reference: https://github.com/starkware-libs/cairo-lang/blob/9e6e0e96d208608d98635ccfad5b26285c4936e1/src/starkware/cairo/stark_verifier/core/proof_of_work.cairo

**Comment by Okm165** [comment]
@tiagofneto @neotheprogramist do we have any progress here?
Verify Proof of Work is the next thing I need for stark-verify task
I can take this task so it unblocks me
Lmk what we do, Cheers

**Comment by neotheprogramist** [comment]
@Okm165 
Feel free to take it
